package com.example.gameon.classes

data class Admin(
    val admin_id: Int? = null, //autogenerated on server side
    val discord_id: String? = null,
    val user: User? = null,
) {
    // The below init requirement causes errors in getAdmins()
//    init {
//        require( discord_id != null || user != null ) {
//            "Either discord_id or user must not be null"
//        }
//    }
}
