package com.example.gameon.classes

import android.os.Parcelable
import kotlinx.parcelize.Parcelize
import java.util.Date

@Parcelize
data class Group(
    val group_id: Int? = null, //autogenerated on server side
    val group_name: String,
    val created_at: Date? = null, //autogenerated on server side
    val max_players: Int,
    val game_id: Int? = null,
    val game: Game? = null,
    val members: List<GroupMember>? = null
) : Parcelable {
    init {
        require(game_id != null || game != null) {
            "Either game_id or game must be non-null"
        }
    }
}