package com.example.gameon.classes

import java.util.Date

data class Report(
    val report_id: Int? = null, //autogenerated on server side
    val reporter_discord_id: String? = null, //Reporter contained in session data
    val reporter: User? = null,
    val reported_discord_id: String? = null,
    val reported_user: User? = null,
    val group_id: Int? = null,
    val group: Group? = null,
    val reason: String,
    val reported_at: Date? = null, //autogenerated on server side
    val resolved: Boolean = false
) {
    init {

//        require( reporter_discord_id != null || reporter != null ) {
//            "Either reporter_discord_id or reporter must not be null"
//        }
        require( reported_discord_id != null || reported_user != null ) {
            "Either reported_discord_id or reported_user must not be null"
        }
        require( group_id != null || group != null ) {
            "Either group_id or group must not be null"
        }
    }
}